name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libgl1

    - name: Configure venv
      run: |
        python3 -m venv venv
        
    - name: Install dependencies
      run: |
        ./venv/bin/python -m pip install --upgrade pip
        ./venv/bin/python -m pip install -r requirements.txt pylint
        
    - name: Analysing the code with pylint
      run: |
        ./venv/bin/python -m pylint --rcfile .pylintrc $(git ls-files '*.py')
